#image: node:16.10.0
#
#pages:
#  script:
#    - yarn
#    - yarn build-storybook
#  artifacts:
#    paths:
#      - public
#  only:
#    - main

default:
  image: node:16
  # Cache node_modules
  cache: &global_cache
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull

stages:
  - install
  - build
  - test
  - publish
  - release

.all_rules: &run_on_all_rules
  rules:
    - &run_for_new_lib_version # Run if semver tag is pushed to any branch
      if: '$CI_COMMIT_TAG =~ /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/'
      # New rule for prereleases?

    - &run_for_new_themes_version # Run if semver tag is pushed to any branch
      if: '$CI_COMMIT_TAG =~ /^@te-whatu-ora\/anatomic-themes@([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/'
      # New rule for prereleases?

    - &run_for_chromatic
      if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

    - &run_for_chromatic_main
      if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
      allow_failure: true

install:
  stage: install
  cache:
    <<: *global_cache
    # override the policy to be able to update node_modules
    policy: pull-push
  script:
    - yarn install

build:
  stage: build
  script:
    - yarn build
    - yarn build-storybook

#👇Checks if the branch is main and runs Chromatic with the flag to accept all changes.
chromatic_publish_auto_accept_changes:
  stage: test
  script:
    - yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --auto-accept-changes --dry-run
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

#👇Checks if the branch is not main and runs Chromatic
chromatic_publish:
  stage: test
  script:
    - yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --dry-run
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
      allow_failure: true

npm_lib_publish:
  rules:
    - *run_for_new_lib_version
  stage: publish
  needs:
    - job: install
      artifacts: true
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - # yarn publish --cwd ./packages/lib

npm_themes_publish:
  rules:
    - *run_for_new_themes_version
  stage: publish
  needs:
    - job: install
      artifacts: true
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    - # yarn publish --cwd ./packages/themes

release:
  rules:
    - *run_for_new_lib_version
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - install
    - npm_lib_publish
  script:
    - echo "Running release_job for $CI_COMMIT_TAG"

  release:
    name: '$CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    description: 'CURRENT_VERSION.md'
    assets:
      links:
        - name: '@te-whatu-ora/anatomic'
          url: 'https://www.npmjs.com/package/@te-whatu-ora/anatomic'
          link_type: 'other' # optional