/**
 * Do not edit directly
 * Generated on Mon, 02 May 2022 22:43:11 GMT
 */

export const tokens = Object.freeze({
  "1": "1",
  "2": "2",
  "10": {
    color: "#4040401a",
    type: "dropShadow",
    x: "0",
    y: "4",
    blur: "30",
    spread: "0",
  },
  colors: {
    primary0: "#ffffff",
    primary5: "#f5f5f5",
    primary25: "#cfcfcf",
    primary50: "#9f9f9f",
    primary75: "#707070",
    primary100: "#404040",
    primary110: "#1c1c1c",
    secondary0: "#ffffff",
    secondary5: "#f9f9f9",
    secondary25: "#dfdfdf",
    secondary50: "#bfbfbf",
    secondary75: "#a0a0a0",
    secondary100: "#808080",
    secondary110: "#464646",
    tertiary0: "#ffffff",
    tertiary5: "#f5f5f5",
    tertiary25: "#cfcfcf",
    tertiary50: "#9f9f9f",
    tertiary75: "#707070",
    tertiary100: "#404040",
    tertiary110: "#131313",
    positive0: "#ffffff",
    positive5: "#f0f5f6",
    positive25: "#c4ddd9",
    positive50: "#8dbeb4",
    positive75: "#569f90",
    positive100: "#1f816c",
    positive110: "#16594b",
    info0: "#ffffff",
    info5: "#eef4fa",
    info25: "#bcd9ed",
    info50: "#7eb6dc",
    info75: "#3f93cc",
    info100: "#0071bc",
    info110: "#005c99",
    caution0: "#000000",
    caution5: "#fbf8f2",
    caution25: "#fbebc8",
    caution50: "#fbdb93",
    caution75: "#fcca5e",
    caution100: "#fcba29",
    caution110: "#cd9821",
    error0: "#ffffff",
    error5: "#faf0f0",
    error25: "#f3c3be",
    error50: "#ec8b7f",
    error75: "#e4533f",
    error100: "#dd1b00",
    error110: "#c71800",
    neutral0: "#ffffff",
    neutral5: "#f2f2f2",
    neutral25: "#bfbfbf",
    neutral50: "#808080",
    neutral75: "#404040",
    neutral100: "#000000",
    annotation0: "#ffffff",
    annotation5: "#f8f7ff",
    annotation25: "#ded7ff",
    annotation50: "#bdb0ff",
    annotation75: "#9c88ff",
    annotation100: "#7b61ff",
    annotation110: "#644ecf",
    visited100: "#5c1893",
  },
  Card: "8",
  Desktop: {
    "3XL": {
      Black: {
        fontFamily: "Fira Sans",
        fontWeight: "Black",
        lineHeight: "115%",
        fontSize: "120",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
    "2XL": {
      Black: {
        fontFamily: "Fira Sans",
        fontWeight: "Black",
        lineHeight: "120%",
        fontSize: "40",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      Bold: {
        fontFamily: "Fira Sans",
        fontWeight: "Bold",
        lineHeight: "120%",
        fontSize: "40",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
    XL: {
      Bold: {
        fontFamily: "Fira Sans",
        fontWeight: "Bold",
        lineHeight: "120%",
        fontSize: "32",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      Regular: {
        fontFamily: "Fira Sans",
        fontWeight: "Regular",
        lineHeight: "120%",
        fontSize: "32",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
    L: {
      Bold: {
        fontFamily: "Fira Sans",
        fontWeight: "Bold",
        lineHeight: "130%",
        fontSize: "24",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      Regular: {
        fontFamily: "Fira Sans",
        fontWeight: "Regular",
        lineHeight: "130%",
        fontSize: "24",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
    M: {
      Bold: {
        fontFamily: "Fira Sans",
        fontWeight: "Bold",
        lineHeight: "160%",
        fontSize: "20",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      Medium: {
        fontFamily: "Fira Sans",
        fontWeight: "Medium",
        lineHeight: "160%",
        fontSize: "20",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      Regular: {
        fontFamily: "Fira Sans",
        fontWeight: "Regular",
        lineHeight: "160%",
        fontSize: "20",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      "Link-Normal": {
        fontFamily: "Fira Sans",
        fontWeight: "Medium",
        lineHeight: "160%",
        fontSize: "20",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      "Link-Hover&Focus": {
        fontFamily: "Fira Sans",
        fontWeight: "Medium",
        lineHeight: "160%",
        fontSize: "20",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "underline",
        textCase: "none",
      },
      Button: {
        fontFamily: "Fira Sans",
        fontWeight: "Bold",
        lineHeight: "130%",
        fontSize: "20",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
    S: {
      Bold: {
        fontFamily: "Fira Sans",
        fontWeight: "Bold",
        lineHeight: "160%",
        fontSize: "18",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      Regular: {
        fontFamily: "Fira Sans",
        fontWeight: "Regular",
        lineHeight: "160%",
        fontSize: "18",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
    XS: {
      Bold: {
        fontFamily: "Fira Sans",
        fontWeight: "Bold",
        lineHeight: "160%",
        fontSize: "16",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
      Regular: {
        fontFamily: "Fira Sans",
        fontWeight: "Regular",
        lineHeight: "160%",
        fontSize: "16",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
  },
  Mobile: {
    "3XL": {
      Black: {
        fontFamily: "Fira Sans",
        fontWeight: "Black",
        lineHeight: "115%",
        fontSize: "40",
        letterSpacing: "0%",
        paragraphSpacing: "0",
        textDecoration: "none",
        textCase: "none",
      },
    },
    "2XL": "48",
    XL: "40",
    L: "32",
    M: "24",
    S: "16",
    XS: "8",
  },
  Primary: {
    "0": "#FFFFFF",
    "5": "#F5F5F5",
    "25": "#CFCFCF",
    "50": "#9F9F9F",
    "75": "#707070",
    "100": "#404040",
    "110": "#1c1c1c",
  },
  Secondary: {
    "0": "#FFFFFF",
    "5": "#F9F9F9",
    "25": "#DFDFDF",
    "50": "#BFBFBF",
    "75": "#A0A0A0",
    "100": "#808080",
    "110": "#464646",
  },
  Tertiary: {
    "0": "#FFFFFF",
    "5": "#F5F5F5",
    "25": "#CFCFCF",
    "50": "#9F9F9F",
    "75": "#707070",
    "100": "#404040",
    "110": "#131313",
  },
  Neutral: {
    "0": "#FFFFFF",
    "5": "#F2F2F2",
    "25": "#BFBFBF",
    "50": "#808080",
    "75": "#404040",
    "100": "#000000",
  },
  Positive: {
    "0": "#FFFFFF",
    "5": "#F0F5F6",
    "25": "#C4DDD9",
    "50": "#8DBEB4",
    "75": "#569F90",
    "100": "#1F816C",
    "110": "#16594B",
  },
  Info: {
    "0": "#FFFFFF",
    "5": "#EEF4FA",
    "25": "#BCD9ED",
    "50": "#7EB6DC",
    "75": "#3F93CC",
    "100": "#0071BC",
    "110": "#005C99",
  },
  Caution: {
    "0": "#000000",
    "5": "#FBF8F2",
    "25": "#FBEBC8",
    "50": "#FBDB93",
    "75": "#FCCA5E",
    "100": "#FCBA29",
    "110": "#CD9821",
  },
  Error: {
    "0": "#FFFFFF",
    "5": "#FAF0F0",
    "25": "#F3C3BE",
    "50": "#EC8B7F",
    "75": "#E4533F",
    "100": "#DD1B00",
    "110": "#C71800",
  },
  Button: {
    " TopLeft": "8",
    " TopRight": "8",
    " BottomLeft": "8",
    " BottomRight": "8",
  },
  Annotation: {
    "0": "#ffffff",
    "5": "#F8F7FF",
    "25": "#DED7FF",
    "50": "#BDB0FF",
    "75": "#9C88FF",
    "100": "#7B61FF",
    "110": "#644ECF",
  },
  Inputs: {
    " TopLeft": "8",
    " TopRight": "8",
    " BottomRight": "8",
    " BottomLeft": "8",
  },
  Visited: { "100": "#5C1893" },
  Tags: { " All corners": "100" },
  font: {
    desktop: {
      "3xl": {
        black: {
          fontSize: 120,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 138,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      "2xl": {
        black: {
          fontSize: 40,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 48,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bold: {
          fontSize: 40,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 48,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xl: {
        bold: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      l: {
        bold: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 31.2,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 31.2,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      m: {
        bold: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        medium: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-normal": {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-hover&focus": {
          fontSize: 20,
          textDecoration: "underline",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        button: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 26,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bullet: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        number: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      s: {
        bold: {
          fontSize: 18,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 18,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xs: {
        bold: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
    },
    mobile: {
      "3xl": {
        black: {
          fontSize: 40,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 46,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      "2xl": {
        black: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bold: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xl: {
        bold: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      l: {
        bold: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 26,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 26,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      m: {
        bold: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        medium: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-normal": {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-hover&focus": {
          fontSize: 16,
          textDecoration: "underline",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        button: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 20.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bullet: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        number: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      s: {
        bold: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xs: {
        bold: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
    },
  },
  typography: {
    desktop: {
      "3xl": {
        black: {
          fontSize: 120,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 138,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      "2xl": {
        black: {
          fontSize: 40,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 48,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bold: {
          fontSize: 40,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 48,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xl: {
        bold: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      l: {
        bold: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 31.2,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 31.2,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      m: {
        bold: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        medium: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-normal": {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-hover&focus": {
          fontSize: 20,
          textDecoration: "underline",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        button: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 26,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bullet: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        number: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 32,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      s: {
        bold: {
          fontSize: 18,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 18,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xs: {
        bold: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
    },
    mobile: {
      "3xl": {
        black: {
          fontSize: 40,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 46,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      "2xl": {
        black: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 900,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bold: {
          fontSize: 32,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 38.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xl: {
        bold: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 24,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 28.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      l: {
        bold: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 26,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 20,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 26,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      m: {
        bold: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        medium: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-normal": {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        "link-hover&focus": {
          fontSize: 16,
          textDecoration: "underline",
          fontFamily: "Fira Sans",
          fontWeight: 500,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        button: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 20.8,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        bullet: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        number: {
          fontSize: 16,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 25.6,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      s: {
        bold: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
      xs: {
        bold: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 700,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
        regular: {
          fontSize: 14,
          textDecoration: "none",
          fontFamily: "Fira Sans",
          fontWeight: 400,
          fontStyle: "normal",
          fontStretch: "normal",
          letterSpacing: 0,
          lineHeight: 22.4,
          paragraphIndent: 0,
          paragraphSpacing: 0,
          textCase: "none",
        },
      },
    },
  },
  grid: {
    desktop: {
      pattern: "columns",
      gutterSize: 32,
      alignment: "stretch",
      count: 12,
      offset: 120,
    },
    mobile: {
      pattern: "columns",
      gutterSize: 8,
      alignment: "stretch",
      count: 2,
      offset: 16,
    },
  },
});
