name: Build

# on:
#   workflow_call:
#     outputs:
#       cache-key:
#         description: "Unique key for caching node_modules from yarn.lock files"
#         value: ${{ jobs.build.outputs.cache-key }}
#       main-repo:
#         description: "Name of the main pattern-library repo"
#         value: tewhatuora/pattern-library

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '@te-whatu-ora/*-themes@[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main
      - '*actions*' # A temp trigger to test workflows - remove in prod


jobs:

  build:
    name: Build packages
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.gen-key.outputs.key }}
      main-repo: 'tewhatuora/pattern-library'
      is-full-lib: ${{ steps.components.outputs.is-full-lib }}
      is-pre-lib: ${{ steps.components.outputs.is-pre-lib }}
      is-full-theme: ${{ steps.components.outputs.is-full-theme }}
      is-pre-theme: ${{ steps.components.outputs.is-pre-theme }}
    steps:

    - name: determine components to act on
      id: components
      run: |
        full-lib=$(echo ${{ github.ref }} | grep -Pq "^refs/tags/v\d+\.\d+\.\d+$" && echo 'true' || echo 'false')
        echo "is-full-lib=${full-lib}" >> $GITHUB_OUTPUT
        pre-lib=$(echo ${{ github.ref }} | grep -Pq "^refs/tags/v\d+\.\d+\.\d+-[\w\.-]+$" && echo 'true' || echo 'false')
        echo "is-pre-lib=${pre-lib}" >> $GITHUB_OUTPUT
        full-theme=$(echo ${{ github.ref }} | grep -Pq "^refs/tags/@te-whatu-ora/[\w-]+-themes@\d+\.\d+\.\d+$" && echo 'true' || echo 'false')
        echo "is-full-theme=${full-theme}" >> $GITHUB_OUTPUT
        pre-theme=$(echo ${{ github.ref }} | grep -Pq "^refs/tags/@${theme-package}@\d+\.\d+\.\d+-[\w\.-]+$" && echo 'true' || echo 'false')
        echo "is-pre-theme=${pre-theme}" >> $GITHUB_OUTPUT

    - name: log component values
      run: |
        echo is-full-lib '${{ steps.components.outputs.is-full-lib }}'
        echo is-pre-lib '${{ steps.components.outputs.is-pre-lib }}'
        echo is-full-theme '${{ steps.components.outputs.is-full-theme }}'
        echo is-pre-theme '${{ steps.components.outputs.is-pre-theme }}'

    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: generate cache key
      id: gen-key
      run: |
        os="${{ runner.os }}"
        node="${{ steps.node-setup.outputs.node-version }}"
        hash="${{ hashFiles('**/yarn.lock') }}"
        echo "key=${os}-node-${node}-${hash}" >> $GITHUB_OUTPUT

    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-prev-cache
      with:
        path: node_modules
        key: ${{ steps.gen-key.outputs.key }}

    - name: yarn install
      if: steps.restore-prev-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: save install cache
      if: steps.restore-prev-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      id: save-cache
      with:
        path: node_modules
        key: ${{ steps.gen-key.outputs.key }}
    
    - name: yarn build
      run: yarn build

    - name: yarn build storybook
      run: yarn build-storybook

    - name: Upload build artifacts
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: pattern-lib-build
        path: "**/dist/"
        if-no-files-found: error

  test:
    if: github.repository == needs.build.outputs.main-repo
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      cache-key: ${{ needs.build.outputs.cache-key }}
      main-repo: ${{ needs.build.outputs.main-repo }}

  publish:
    if: github.repository == needs.build.outputs.main-repo
    needs: build
    uses: ./.github/workflows/publish.yml
    with:
      cache-key: ${{ needs.build.outputs.cache-key }}
      main-repo: ${{ needs.build.outputs.main-repo }}
      is-full-lib: ${{ needs.build.outputs.is-full-lib }}
      is-pre-lib: ${{ needs.build.outputs.is-pre-lib }}
      is-full-theme: ${{ needs.build.outputs.is-full-theme }}
      is-pre-theme: ${{ needs.build.outputs.is-pre-theme }}
  
  release:
    if: github.repository == needs.build.outputs.main-repo
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      cache-key: ${{ needs.build.outputs.cache-key }}
      main-repo: ${{ needs.build.outputs.main-repo }}
      is-full-lib: ${{ needs.build.outputs.is-full-lib }}
