name: Build

on:
  workflow_call:
    outputs:
      cache-key:
        description: "Unique key for caching node_modules from yarn.lock files"
        value: ${{ jobs.build.outputs.cache-key }}
      artifact-id:
        description: "ID of uploaded artifact"
        value: ${{ jobs.build.outputs.artifact-id }}
      on-main-repo:
        description: "Whether workflows are running from the main pattern-library repo"
        value: ${{ jobs.build.outputs.on-main-repo }}

jobs:

  install:
    uses: ./.github/workflows/install.yml

  build:
    name: Build packages
    needs: install
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ needs.install.outputs.cache-key }}
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
      on-main-repo: ${{ needs.install.outputs.on-main-repo }}
    #if: ${{ needs.install.outputs.on-main-repo == true }}
    steps:
    # - name: logs
    #   run: echo "${{ toJson(needs.install.outputs) }}"

    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
  
    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-install-cache
      with:
        path: node_modules
        key: ${{ needs.install.outputs.cache-key }}
    
    - name: yarn build
      run: yarn build

    - name: yarn build storybook
      run: yarn build-storybook

    - name: Upload build artifacts
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: pattern-lib-build
        path: "**/dist/"
        if-no-files-found: error