# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# TODO - restructure and clean up. eg make DRYer, and possibly split into multiple workflows?

name: Build

on:
  push:
    branches:
      - main
      - '*actions*' # A temp trigger to test workflows

jobs:

  info:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
      main-repo: ${{ github.repository == 'tewhatuora/pattern-library' }}
      new-lib: ${{ github.ref_type == 'tag' && steps.new-lib.outputs.match != '' }}
      new-theme: ${{ github.ref_type == 'tag' && steps.new-theme.outputs.match != '' }}

    steps:
      - uses: actions/checkout@v4
      - id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - id: cache-key
        run: |
          os="${{ runner.os }}"
          node="${{ steps.node-setup.outputs.node-version }}"
          hash="${{ hashFiles('**/yarn.lock') }}"
          echo "key=${os}-node-${node}-${hash}" >> $GITHUB_OUTPUT
      - id: new-lib
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref_name }}
          regex: '^v([0-9]+)\.([0-9]+)\.([0-9]+)?$'
      - id: new-theme
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref_name }}
          regex: '^@te-whatu-ora\/anatomic-themes@([0-9]+)\.([0-9]+)\.([0-9]+)?$'

  install:
    needs: info
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-prev-cache
      with:
        path: node_modules
        #key: ${{ runner.os }}-node-${{ steps.node-setup.outputs.node-version }}-${{ hashFiles('**/yarn.lock') }}
        key: ${{ needs.info.outputs.cache-key }}

    - name: yarn install
      if: steps.restore-prev-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: save install cache
      if: steps.restore-prev-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      id: save-cache
      with:
        path: node_modules
        #key: ${{ steps.restore-prev-cache.outputs.cache-primary-key }}
        key: ${{ needs.info.outputs.cache-key }}

  build:
    needs: [info, install]
    runs-on: ubuntu-latest
    if: ${{ needs.info.outputs.main-repo }}
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
  
    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-install-cache
      with:
        path: node_modules
        #key: ${{ runner.os }}-node-${{ steps.node-setup.outputs.node-version }}-${{ hashFiles('**/yarn.lock') }}
        key: ${{ needs.info.outputs.cache-key }}
    
    - name: yarn build
      run: yarn build

    - name: yarn build storybook
      run: yarn build-storybook