name: Install

on:
  workflow_call:
    outputs:
      node-version:
        description: "NodeJS version from .nvmrc file"
        value: ${{ jobs.install.outputs.node }}
      cache-key:
        description: "Unique key for caching node_modules from yarn.lock files"
        value: ${{ jobs.install.outputs.cache-key }}
      on-main-repo:
        description: "Whether workflows are running from the main pattern-library repo"
        value: ${{ jobs.install.outputs.on-main-repo }}

jobs:
  init:
    uses: ./.github/workflows/init.yml

  install:
    needs: init
    runs-on: ubuntu-latest
    outputs:
      node: ${{ needs.init.outputs.node-version }}
      cache-key: ${{ needs.init.outputs.cache-key }}
      on-main-repo: ${{ needs.init.outputs.on-main-repo }}

    steps:
    - name: logs
      run: echo "${{ toJson(needs.init.outputs) }}"

    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-prev-cache
      with:
        path: node_modules
        key: ${{ needs.init.outputs.cache-key }}

    - name: yarn install
      if: steps.restore-prev-cache.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: save install cache
      if: steps.restore-prev-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      id: save-cache
      with:
        path: node_modules
        key: ${{ needs.init.outputs.cache-key }}

