name: Publish lib

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
      main-repo:
        required: true
        type: string
      is-full-lib:
        type: string # 'true' or 'false'
      is-pre-lib:
        type: string # 'true' or 'false'
      is-full-theme:
        type: string # 'true' or 'false'
      is-pre-theme:
        type: string # 'true' or 'false'
  # push:
  #   tags:
  #     - 'v[0-9]+.[0-9]+.[0-9]+'
  #   branches:
  #     - '*actions*' # A temp trigger to test workflows - remove in prod

jobs:
  # build:
  #   uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    #needs: build
    if: github.repository == inputs.main-repo
    steps:

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
  
    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-install-cache
      with:
        path: node_modules
        key: ${{ inputs.cache-key }}
    
    - name: download build artifact
      uses: actions/download-artifact@v4

    - name: publish library
      if: false
      run: |
        npm config set '//registry.npmjs.org/:_authToken' ${{ env.NPM_TOKEN }}
        yarn publish --cwd ./packages/lib --tag latest

    - name: publish prerelease library
      if: false
      run: |
        PRE_RELEASE_VERSION=${${{ github.ref_name }}#*.[0-9]*-}
        TAG_NAME=${PRE_RELEASE_VERSION%.*}
        echo $TAG_NAME
        npm config set '//registry.npmjs.org/:_authToken' ${{ env.NPM_TOKEN }}
        yarn publish --cwd ./packages/lib --tag $TAG_NAME

    - name: publish theme
      if: false
      run: |
        npm config set '//registry.npmjs.org/:_authToken' ${{ env.NPM_TOKEN }}
        yarn publish --cwd ./packages/theme --tag latest

    - name: publish prerelease theme
      if: false
      run: |
        PRE_RELEASE_VERSION=${${{ github.ref_name }}#*.[0-9]*-}
        TAG_NAME=${PRE_RELEASE_VERSION%.*}
        echo $TAG_NAME
        npm config set '//registry.npmjs.org/:_authToken' ${{ env.NPM_TOKEN }}
        yarn publish --cwd ./packages/theme --tag $TAG_NAME
