name: Test

# on:
#   pull_request:
#   push: # A temp trigger to test workflows - remove in prod
#     branches:
#       - '*actions*'

on:
  workflow_call:

jobs:
  # build:
  #   uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    #needs: build
    #if: github.repository == needs.build.outputs.main-repo
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
  
    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-install-cache
      with:
        path: node_modules
        key: ${{ needs.build.outputs.cache-key }}
    
    - name: download build artifact
      uses: actions/download-artifact@v4

    - name: Run push tests
      if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main' }}
      run: echo This is the command for running the tests
      # gitlab ci version:
      # yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --auto-accept-changes

    - name: Run PR tests
      if: ${{ github.event_name == 'pull_request' }}
      run: echo This is the command for running the PR tests
      # gitlab ci version:
      # yarn chromatic --branch-name $CI_COMMIT_REF_SLUG