name: Test PR

on:
  pull_request:
  push:
    branches:
      - '*actions*' # A temp trigger to test workflows

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: placeholder
      run: echo hello
