name: Test

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string

jobs:

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
  
    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-install-cache
      with:
        path: node_modules
        key: ${{ inputs.cache-key }}
    
    - name: download build artifact
      uses: actions/download-artifact@v4

    - name: Run push tests
      if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main' }}
      run: |
        yarn chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --auto-accept-changes

    - name: Run PR tests
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        yarn chromatic --branch-name ${{ github.ref_name }}
