name: Test

# on:
#   pull_request:
#   push: # A temp trigger to test workflows - remove in prod
#     branches:
#       - '*actions*'

on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
      main-repo:
        required: true
        type: string

jobs:
  # build:
  #   uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    #needs: build
    if: github.repository == inputs.main-repo
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: setup node
      id: node-setup
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
  
    - name: restore cache
      uses: actions/cache/restore@v4
      id: restore-install-cache
      with:
        path: node_modules
        key: ${{ inputs.cache-key }}
    
    - name: download build artifact
      uses: actions/download-artifact@v4

    - name: Run push tests
      if: ${{ github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main' }}
      run: |
        echo This is the command for running the push tests:
        echo yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --auto-accept-changes
      # yarn chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --auto-accept-changes

    - name: Run PR tests
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo This is the command for running the PR tests
        echo yarn chromatic --branch-name ${{ github.ref_name }}
      # yarn chromatic --branch-name ${{ github.ref_name }}
